version: "3.8"
services:
  db:
    # platform: linux/arm64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 02052002Dat@
      MYSQL_DATABASE: cds
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: